variables:
  HTTP_PROXY: http://proxy3.lmco.com:80
  HTTPS_PROXY: http://proxy3.lmco.com:80
  http_proxy: http://proxy3.lmco.com:80
  https_proxy: http://proxy3.lmco.com:80
  NO_PROXY: 127.0.0.1,localhost

stages:
  - Build
  - Test

.docker-mongo: &docker-mongo
  image: registry.gitlab.us.lmco.com:443/mbx/mbee/mcf/gitlab-docker-build-image:latest
  tags:
    - docker
  services: 
    - name: registry.gitlab.us.lmco.com:443/mbx/mbee/mcf/mongo:4.0.4
      alias: mongodb

Build MCF:
  <<: *docker-mongo
  # image: registry.gitlab.us.lmco.com:443/mbx/mbee/mcf/gitlab-docker-build-image:latest
  # tags:
  #   - docker
  stage: Build
  dependencies: []
  script:
    - export HTTP_PROXY=http://proxy3.lmco.com:80
    - export HTTPS_PROXY=http://proxy3.lmco.com:80
    - export NO_PROXY=127.0.0.1,localhost
    - yarn config set strict-ssl false
    - yarn config set proxy http://proxy3.lmco.com:80
    - yarn config set https-proxy http://proxy3.lmco.com:80
    - yarn config set no_proxy 127.0.0.1,localhost
    - NOPREINSTALL=1 yarn install
    - node mbee migrate -y

Run MCF:
  <<: *docker-mongo
  # image: registry.gitlab.us.lmco.com:443/mbx/mbee/mcf/gitlab-docker-build-image:latest
  # tags:
  #   - docker
  stage: Test
  dependencies: []
  script:
    - node mbee start

Test MCF:
  <<: *docker-mongo
  stage: Test
  dependencies: []
  script:
    - sleep 15
    - node mbee lint
    - sleep 5
    - node mbee test --all
