variables:
  HTTP_PROXY: http://proxy3.lmco.com:80
  HTTPS_PROXY: http://proxy3.lmco.com:80
  http_proxy: http://proxy3.lmco.com:80
  https_proxy: http://proxy3.lmco.com:80
  NO_PROXY: 127.0.0.1,localhost
  GIT_SSL_NO_VERIFY: "true"
  GIT_STRATEGY: clone
  MBEE_ENV: pipeline
  DTR_URL: dtr.mbx.us.lmco.com
  DTR_ORG: mbee
  DTR_REPO: mcf
  DTR_TAG: latest

stages:
  # - Build
  - Test
  - Docker

# Build MCF:
#   stage: Build
#   tags:
#     - docker
#   image: registry.gitlab.us.lmco.com:443/mbx/mbee/mcf/gitlab-docker-build-image:latest
#   before_script:
#     - export HTTP_PROXY=$HTTP_PROXY
#     - export HTTPS_PROXY=$HTTPS_PROXY
#     - export NO_PROXY=$NO_PROXY
#     - yarn config set strict-ssl false
#     - yarn config set proxy $HTTP_PROXY
#     - yarn config set https-proxy $HTTPS_PROXY
#     - yarn config set no_proxy $NO_PROXY
#   script:
#     - NOPREINSTALL=1 yarn install
#     - node mbee lint

Test MCF:
  stage: Test
  artifacts:
    paths:
    - node_modules
    - yarn.lock
    - build
    - plugins
    - coverage
    expire_in: 2h
  tags:
    - docker
  image: registry.gitlab.us.lmco.com:443/mbx/mbee/mcf/gitlab-docker-build-image:latest
  services:
    - name: registry.gitlab.us.lmco.com:443/mbx/mbee/mcf/mongo:4.0.4
      alias: mongodb
    - name: registry.gitlab.us.lmco.com:443/mbx/mbee/mcf/redis:6.0.9
      alias: redis_pipeline
  before_script:
    - export MBEE_ENV=$MBEE_ENV
    - export HTTP_PROXY=$HTTP_PROXY
    - export HTTPS_PROXY=$HTTPS_PROXY
    - export NO_PROXY=$NO_PROXY
    - yarn config set strict-ssl false
    - yarn config set proxy $HTTP_PROXY
    - yarn config set https-proxy $HTTPS_PROXY
    - yarn config set no_proxy $NO_PROXY
    - NOPREINSTALL=1 yarn install
    - node mbee migrate -y
  script:
    - hostname
    - docker ps
    - echo $MBEE_ENV
    - nohup node mbee start &
    - sleep 20
    - yarn testall

Test Plugins:
  stage: Test
  tags:
    - docker
  image: registry.gitlab.us.lmco.com:443/mbx/mbee/mcf/gitlab-docker-build-image:latest
  services:
    - name: registry.gitlab.us.lmco.com:443/mbx/mbee/mcf/mongo:4.0.4
      alias: mongodb
    - name: registry.gitlab.us.lmco.com:443/mbx/mbee/mcf/redis:6.0.9
      alias: redis
  before_script:
    - export MBEE_ENV=$MBEE_ENV
    - export HTTP_PROXY=$HTTP_PROXY
    - export HTTPS_PROXY=$HTTPS_PROXY
    - export NO_PROXY=$NO_PROXY
    - yarn config set strict-ssl false
    - yarn config set proxy $HTTP_PROXY
    - yarn config set https-proxy $HTTPS_PROXY
    - yarn config set no_proxy $NO_PROXY
    - NOPREINSTALL=1 yarn install
    - node mbee migrate -y
  script:
    - node mbee test --plugins

Docker Build MCF:
  stage: Docker
  tags:
    - shell
  only:
    - develop
    - /^release\/.*$/
    - /^prc\/.*$/
  dependencies:
    - Test MCF
  script:
    - export DTR_URI=$DTR_URL/$DTR_ORG/$DTR_REPO
    - docker build -t mcf-docker .
    - docker tag mcf-docker registry.gitlab.us.lmco.com:443/mbx/mbee/mcf/mcf-docker
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN registry.gitlab.us.lmco.com:443
    - docker push registry.gitlab.us.lmco.com:443/mbx/mbee/mcf/mcf-docker:latest
    - docker tag mcf-docker $DTR_URI:$DTR_TAG
    - docker login $DTR_URL -u "$DTR_USER" -p $DTR_API_KEY
    - docker push $DTR_URI:$DTR_TAG
