variables:
  HTTP_PROXY: http://proxy3.lmco.com:80
  HTTPS_PROXY: http://proxy3.lmco.com:80
  http_proxy: http://proxy3.lmco.com:80
  https_proxy: http://proxy3.lmco.com:80
  NO_PROXY: 127.0.0.1,localhost

stages:
  - Build
  - Test
  - Prep DevOps
  - test2

.run-docker-image: &run-docker-image
  image: registry.gitlab.us.lmco.com:443/mbx/mbee/mcf/gitlab-docker-build-image:latest
  tags:
    - shell

Build MCF:
  <<: *run-docker-image
  stage: Build
  dependencies: []
  script:
    - export HTTP_PROXY=http://proxy3.lmco.com:80
    - export HTTPS_PROXY=http://proxy3.lmco.com:80
    - export NO_PROXY=127.0.0.1,localhost
    - node -v
    - yarn -v
    - NOPOSTINSTALL=1 NOPREINSTALL=1 yarn install
    - node mbee migrate -y
    - sleep 5
    - node mbee test
