variables:
  HTTP_PROXY: http://proxy3.lmco.com:80
  HTTPS_PROXY: http://proxy3.lmco.com:80
  http_proxy: http://proxy3.lmco.com:80
  https_proxy: http://proxy3.lmco.com:80
  NO_PROXY: 127.0.0.1,localhost

stages:
  - Build



.docker-mongo: &docker-mongo
  image: registry.gitlab.us.lmco.com:443/mbx/mbee/mcf/gitlab-docker-build-image:latest
  tags:
    - docker
  services: 
    - name: registry.gitlab.us.lmco.com:443/mbx/mbee/mcf/mongo:4.0.4
      alias: mongodb

.mcf-test: &mcf-test
  image: registry.gitlab.us.lmco.com:443/mbx/mbee/mcf/gitlab-docker-build-image:latest
  tags:
    - docker
  services:
    - name: registry.gitlab.us.lmco.com:443/mbx/mbee/mcf/mongo:4.0.4
      alias: mongodb
    - name: registry.gitlab.us.lmco.com:443/mbx/mbee/mcf/mcf-ci:latest
      alias: mcf
  before_script:
    - export HTTP_PROXY=http://proxy3.lmco.com:80
    - export HTTPS_PROXY=http://proxy3.lmco.com:80
    - export NO_PROXY=127.0.0.1,localhost
    - yarn config set strict-ssl false
    - yarn config set proxy http://proxy3.lmco.com:80
    - yarn config set https-proxy http://proxy3.lmco.com:80
    - yarn config set no_proxy 127.0.0.1,localhost
    - NOPREINSTALL=1 yarn install
    - node mbee migrate -y


Build MCF:
  tags:
    -shell
  stage: Build
  dependencies: []
  script:
    - pwd
    - ls
#    - docker build -t mcf-ci -f ./config/gitlab.Dockerfile .
#    - docker tag mcf-ci registry.gitlab.us.lmco.com:443/mbx/mbee/mcf/mcf-ci
#    - docker push registry.gitlab.us.lmco.com:443/mbx/mbee/mcf/mcf-ci:latest

Test MCF:
  <<: *mcf-test
  stage: Test
  dependencies:
    - "Build MCF"
  script:
    - node mbee lint
    - sleep 5
    - node mbee test --all
