variables:
  HTTP_PROXY: http://proxy3.lmco.com:80
  HTTPS_PROXY: http://proxy3.lmco.com:80
  http_proxy: http://proxy3.lmco.com:80
  https_proxy: http://proxy3.lmco.com:80
  NO_PROXY: 127.0.0.1,localhost

stages:
  - Build
  - Test

Build MCF:
  stage: Build
  tags:
    - docker
  image: registry.gitlab.us.lmco.com:443/mbx/mbee/mcf/gitlab-docker-build-image:latest
  dependencies: []
  # artifacts:
  #   paths:
  #   - node_modules
  #   expire_in: 1h
  before_script:
    - export HTTP_PROXY=http://proxy3.lmco.com:80
    - export HTTPS_PROXY=http://proxy3.lmco.com:80
    - export NO_PROXY=127.0.0.1,localhost
    - yarn config set strict-ssl false
    - yarn config set proxy http://proxy3.lmco.com:80
    - yarn config set https-proxy http://proxy3.lmco.com:80
    - yarn config set no_proxy 127.0.0.1,localhost
  script:
    # - docker build -t mcf-ci -f ./config/gitlab.Dockerfile .
    # - docker tag mcf-ci registry.gitlab.us.lmco.com:443/mbx/mbee/mcf/mcf-ci
    # - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN registry.gitlab.us.lmco.com:443
    # - docker push registry.gitlab.us.lmco.com:443/mbx/mbee/mcf/mcf-ci:latest
    - NOPREINSTALL=1 yarn install
    - node mbee lint

Test MCF:
  stage: Test
  tags:
    - docker
  image: registry.gitlab.us.lmco.com:443/mbx/mbee/mcf/gitlab-docker-build-image:latest
  services:
    - name: registry.gitlab.us.lmco.com:443/mbx/mbee/mcf/mongo:4.0.4
      alias: mongodb
  before_script:
    - export HTTP_PROXY=http://proxy3.lmco.com:80
    - export HTTPS_PROXY=http://proxy3.lmco.com:80
    - export NO_PROXY=127.0.0.1,localhost
    - yarn config set strict-ssl false
    - yarn config set proxy http://proxy3.lmco.com:80
    - yarn config set https-proxy http://proxy3.lmco.com:80
    - yarn config set no_proxy 127.0.0.1,localhost
    - NOPREINSTALL=1 yarn install
    # - yarn build
    - node mbee migrate -y
  script:
    # - node mbee lint
    # - sleep 5
    - git clone https://gitlab+deploy-token-781:mcf@gitlab.example.com/tanuki/awesome_project.git
    - nohup node mbee start &
    - sleep 20
    - node mbee test --all

Test Plugins:
  stage: Test
  # trigger:
  #   include: pipepline/config/plugins.yml
  tags:
    - docker
  image: registry.gitlab.us.lmco.com:443/mbx/mbee/mcf/gitlab-docker-build-image:latest
  dependencies: 
    - Build MCF
  services:
    - name: registry.gitlab.us.lmco.com:443/mbx/mbee/mcf/mongo:4.0.4
      alias: mongodb
  before_script:
    - export HTTP_PROXY=http://proxy3.lmco.com:80
    - export HTTPS_PROXY=http://proxy3.lmco.com:80
    - export NO_PROXY=127.0.0.1,localhost
    - yarn config set strict-ssl false
    - yarn config set proxy http://proxy3.lmco.com:80
    - yarn config set https-proxy http://proxy3.lmco.com:80
    - yarn config set no_proxy 127.0.0.1,localhost
  script:
    # - node mbee lint
    # - sleep 5
    # - nohup node mbee start &
    # - sleep 20
    # - node mbee test --all
    - ls
    - echo "Running script for testing plugins"
