variables:
  GIT_SSL_NO_VERIFY: "true"
  GIT_STRATEGY: clone
  MBEE_ENV: pipeline
  DTR_URL: dtr.mbx.us.lmco.com
  DTR_ORG: mbee
  DTR_REPO: mcf
  DTR_TAG: latest

stages:
  - Setup Env
  - Test
  - Docker

Setup Environment:
  stage: Setup Env
  tags:
    - shell
  dependencies:
    - Test MCF
  script:
    - docker build -t pre-mcf-docker .
    - docker tag pre-mcf-docker registry.gitlab.us.lmco.com:443/mbx/mbee/mcf/pre-mcf-docker
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN registry.gitlab.us.lmco.com:443
    - docker push registry.gitlab.us.lmco.com:443/mbx/mbee/mcf/pre-mcf-docker:latest

Build & Test MCF:
  stage: Test
  artifacts:
    paths:
    - node_modules
    - yarn.lock
    - build
    - plugins
    - coverage
    expire_in: 2h
  tags:
    - docker
  image: registry.gitlab.us.lmco.com:443/mbx/mbee/mcf/gitlab-docker-build-image2:latest
  services:
    - name: registry.gitlab.us.lmco.com:443/mbx/mbee/mcf/mongo:4.0.4
      alias: mongodb
    - name: registry.gitlab.us.lmco.com:443/mbx/mbee/mcf/redis:6.0.9
      alias: redis
  before_script:
    - export MBEE_ENV=$MBEE_ENV
    - export HTTP_PROXY=$HTTP_PROXY
    - export HTTPS_PROXY=$HTTPS_PROXY
    - export NO_PROXY=$NO_PROXY
    - yarn config set strict-ssl false
    - yarn config set proxy $HTTP_PROXY
    - yarn config set https-proxy $HTTPS_PROXY
    - yarn config set no_proxy $NO_PROXY
    - NOPREINSTALL=1 yarn install
    - node mbee migrate -y
  script:
    - docker pull registry.gitlab.us.lmco.com:443/mbx/mbee/mcf/pre-mcf-docker:latest
    - docker run -d -p 9080:9080 registry.gitlab.us.lmco.com:443/mbx/mbee/mcf/pre-mcf-docker:latest
    # - nohup node mbee start &
    - sleep 15
    - yarn testall

# Test Plugins:
#   stage: Test
#   tags:
#     - docker
#   image: registry.gitlab.us.lmco.com:443/mbx/mbee/mcf/gitlab-docker-build-image2:latest
#   services:
#     - name: registry.gitlab.us.lmco.com:443/mbx/mbee/mcf/mongo:4.0.4
#       alias: mongodb
#     - name: registry.gitlab.us.lmco.com:443/mbx/mbee/mcf/redis:6.0.9
#       alias: redis
#   before_script:
#     - export MBEE_ENV=$MBEE_ENV
#     - export HTTP_PROXY=$HTTP_PROXY
#     - export HTTPS_PROXY=$HTTPS_PROXY
#     - export NO_PROXY=$NO_PROXY
#     - yarn config set strict-ssl false
#     - yarn config set proxy $HTTP_PROXY
#     - yarn config set https-proxy $HTTPS_PROXY
#     - yarn config set no_proxy $NO_PROXY
#     - NOPREINSTALL=1 yarn install
#     - node mbee migrate -y
#   script:
#     - node mbee test --plugins

Docker Build MCF:
  stage: Docker
  tags:
    - shell
  only:
    - develop
    - /^release\/.*$/
    - /^prc\/.*$/
  dependencies:
    - Test MCF
  script:
    - export DTR_URI=$DTR_URL/$DTR_ORG/$DTR_REPO
    - docker build -t mcf-docker .
    - docker tag mcf-docker registry.gitlab.us.lmco.com:443/mbx/mbee/mcf/mcf-docker
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN registry.gitlab.us.lmco.com:443
    - docker push registry.gitlab.us.lmco.com:443/mbx/mbee/mcf/mcf-docker:latest
    - docker tag mcf-docker $DTR_URI:$DTR_TAG
    - docker login $DTR_URL -u "$DTR_USER" -p $DTR_API_KEY
    - docker push $DTR_URI:$DTR_TAG
