# Service
apiVersion: v1
kind: Service
metadata:
  name: mcf-service
  labels:
    app: mcf
spec:
  ports:
  - name: mcf
    port: 80
    targetPort: 9080
    protocol: TCP
  selector:
    app: mcf

---

# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcf-deployment
  labels:
    app: mcf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcf
  template:
    metadata:
      labels:
        app: mcf
    spec:
      nodeName: test-test # attaches the pod to the test-test node
      dnsPolicy: Default # pod inherits dns name of the node
      imagePullSecrets:
      - name: mcf-repo
      containers:
        - name: mcf
          imagePullPolicy: Always
          image: registry.gitlab.us.lmco.com:443/mbx/mbee/mcf/mcf-docker:latest
          ports:
            - containerPort: 9080
