/******************************************************************************
 * Classification: UNCLASSIFIED                                               *
 *                                                                            *
 * Copyright (C) 2018, Lockheed Martin Corporation                            *
 *                                                                            *
 * LMPI WARNING: This file is Lockheed Martin Proprietary Information.        *
 * It is not approved for public release or redistribution.                   *
 *                                                                            *
 * EXPORT CONTROL WARNING: This software may be subject to applicable export  *
 * control laws. Contact legal and export compliance prior to distribution.   *
 ******************************************************************************/
/**
 * Jenkinsfile
 *
 * Josh Kaplan
 * joshua.d.kaplan@lmco.com
 *
 * This file defines the build pipeline for Jenkins.
 */

pipeline {
    agent any

    stages {
        /**
         * Runs a few sanity-check and cleanup commands.
         */
        stage('Prepare') {
            steps {
                // Clean build env
                sh 'rm -rf node_modules'
                sh 'rm -rf public'
                sh 'rm -rf logs/*'
                sh 'rm -rf *.log'
            }
        }

        /**
         * Builds the production docker image based on the Dockerfile.
         */
        stage('Build') {
            steps {
                sh 'ls -l'
                sh 'NODE_ENV=production node mbee docker --build'
            }
        }

        /**
         * Runs the staging docker container from the production image
         */
        stage('Stage') {
            steps {
                //Removes any existing running or stopped stage containers.
                sh 'NODE_ENV=stage node mbee docker --clean'
                /* Runs the container in the background. */
                sh 'NODE_ENV=stage node mbee docker --run'
            }
        }

        /**
         * Executes functional tests against the staged server.
         */
        stage('Test') {
            steps {
                // Runs the basic test suite against the running stage container
                sh 'NODE_ENV=stage node mbee test --grep "^[0-6]"'
            }
        }

        /**
         * First, stops and removes current container.
         * Then runs the newly built docker container.
         */
        stage('Run') {
            steps {
                // Removes the staged container
                sh 'NODE_ENV=stage node mbee docker --clean'

                // Removes any existing production running containers
                sh 'NODE_ENV=production node mbee docker --clean'


                // Runs the production container in the background
                sh 'NODE_ENV=production node mbee docker --run'
            }
        }

    }
}

