/******************************************************************************
 * Classification: UNCLASSIFIED                                               *
 *                                                                            *
 * Copyright (C) 2018, Lockheed Martin Corporation                            *
 *                                                                            *
 * LMPI WARNING: This file is Lockheed Martin Proprietary Information.        *
 * It is not approved for public release or redistribution.                   *
 *                                                                            *
 * EXPORT CONTROL WARNING: This software may be subject to applicable export  *
 * control laws. Contact legal and export compliance prior to distribution.   *
 ******************************************************************************/
/**
 * Jenkinsfile
 *
 * Josh Kaplan
 * joshua.d.kaplan@lmco.com
 *
 * This file defines the build pipeline for Jenkins.
 */

pipeline {
    agent any

    stages {
        /**
         * Runs a few sanity-check and cleanup commands.
         */
        stage('Prepare') {
            steps {
                // Clean build env
                sh 'rm -rf node_modules'
                sh 'rm -rf public'
                sh 'rm -rf logs/*'
                sh 'rm -rf *.log'
            }
        }

        /**
         * Builds the production docker image based on the Dockerfile.
         */
        stage('Build') {
            steps {
                // Build
                sh 'NODE_ENV=production node mbee build'

                // Verify build
                sh 'ls -l'

                // Build the docker image
                sh 'NODE_ENV=production node mbee docker --build'
            }
        }

        /**
         * Runs the staging docker container from the production image
         */
        stage('Stage') {
            steps {
                //Removes any existing running or stopped stage containers.
                sh 'NODE_ENV=stage node mbee docker --clean'
                /* Runs the container in the background. */
                sh 'NODE_ENV=stage node mbee docker --run'
            }
        }

        /**
         * Executes functional tests against the staged server.
         */
        stage('Test') {
            steps {
                // Wait to be sure server is up
                sh 'sleep 10'
                // Runs the basic test suite against the running stage container
                sh 'NODE_ENV=stage node mbee test --grep "^[0-6]"'
            }
        }

        /**
         * First, stops and removes current container.
         * Then runs the newly built docker container.
         */
        stage('Run') {
            steps {
                // Removes the staged container
                sh 'NODE_ENV=stage node mbee docker --clean'

                // Removes any existing production running containers
                sh 'NODE_ENV=production node mbee docker --clean'

                // Runs the production container in the background
                sh 'NODE_ENV=production node mbee docker --run'
            }
        }

    }

    /**
     * This gets run at the end of the pipeline.
     */
    post {
        success {
            emailext body: "${env.JOB_NAME} - Build # ${env.BUILD_NUMBER} - SUCCESS: \
                \
                Check console output at ${env.BUILD_URL} to view the results.\
                <br/>\
                View Git commit at ${env.GIT_URL} -  ${env.GIT_COMMIT}.",
                mimeType: 'text/html',
                subject: "${env.JOB_NAME} - Build # ${env.BUILD_NUMBER} - SUCCESS!",
                to: "joshua.d.kaplan@lmco.com",
                replyTo: "mbee-service.fc-ssc@lmco.com",
                from: "mbee-service.fc-ssc@lmco.com",
                attachLog: true
        }
        failure {
            emailext body: "${env.JOB_NAME} - Build # ${env.BUILD_NUMBER} - FAILED: \
                <br/>\
                Check console output at ${env.BUILD_URL} to view the results.\
                <br/>\
                View Git commit at ${env.GIT_URL} -  ${env.GIT_COMMIT}.",
                mimeType: 'text/html',
                subject: "${env.JOB_NAME} - Build # ${env.BUILD_NUMBER} - FAILED!",
                to: "joshua.d.kaplan@lmco.com",
                replyTo: "mbee-service.fc-ssc@lmco.com",
                from: "mbee-service.fc-ssc@lmco.com",
                attachLog: true
        }
    }
}

