# PersistentVolumeClaim for dev
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-dev-data-pv
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---

# Persistent Volume for dev
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-dev-data-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: nfs_share_address
    path: "/mnt/mbee/mbee-dev/data"