# PersistentVolumeClaim for test
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-test-data-pv
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---

# Persistent Volume for test
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-test-data-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/mnt/mbee/mbee-test/data"