# Service
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    app: mongo

---

# External service
apiVersion: v1
kind: Service
metadata:
  name: mongo-external-service
spec:
  type: NodePort
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
    nodePort: 30036
    protocol: TCP
  selector:
    app: mongo

---

# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      nodeName: dev-dev # attaches the pod to the dev-dev node
      dnsPolicy: Default # pod inherits dns name of the node
      imagePullSecrets:
      - name: mcf-repo
      containers:
        - name: mongo
          imagePullPolicy: Always
          image: registry.gitlab.us.lmco.com:443/mbx/mbee/mcf/mcf-mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data-volume
              mountPath: /data/db
      volumes:
        - name: mongo-data-volume
          persistentVolumeClaim:
            claimName: mongo-dev-data-pv